

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    env_file:
      - .env  # live code reload during development
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: example   # REQUIRED on first init
        MYSQL_DATABASE: urlshortener       # optional: auto-create DB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: