global:
  scrape_interval: 15s  # scrape every 15 seconds
  evaluation_interval: 15s

scrape_configs:
  # 1️⃣ Flask app metrics (custom Prometheus endpoint)
  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask-app:5000']

  # 2️⃣ Redis metrics via official Redis exporter
  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: ['redis:9121']  # default Redis exporter port

  # 3️⃣ MySQL metrics via official MySQL exporter
  - job_name: mysql # To get metrics about the mysql exporter’s targets
    metrics_path: /probe
    params:
        auth_module: [client.servers]
    static_configs:
        - targets:
          - db:3306
          - db:3306
          - mysql-exporter:9041
    relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          # The mysqld_exporter host:port
          replacement: localhost:9104
